name: Go CI and Release

on:
  push:
    branches:
      - master
env:
  APP_NAME: env-manager
  DIST_DIR: dist

jobs:
  # Test
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'  # Use the Go version of your choice
      
      - name: Lint Check
        run: go vet ./...

      - name: Run tests
        run: go test -v ./...

  # Create release
  create-release:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      RELEASE_URL: ${{ steps.create-release.outputs.upload_url }}
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get Version
        id: get_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false

  build:
    needs: create-release
    strategy:
      matrix:
        os: ['windows', 'linux', 'darwin']
        arch: ['amd64', 'arm64']
        exclude:
          - os: windows
            arch: arm64
          - os: linux
            arch: arm64
          - os: darwin
            arch: amd64
        
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'  # Use the Go version of your choice

      - name: Create distribution directory
        run: mkdir -p ${{ env.DIST_DIR }}
        shell: bash
      
      - name: Build
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ${{ env.DIST_DIR }}/${{ env.APP_NAME }}-${{ matrix.os }}-${{ matrix.arch }}
        env:
          VERSION: ${{ needs.create-release.outputs.VERSION }}
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.RELEASE_URL }}
          asset_path: ${{ env.DIST_DIR }}/${{ env.APP_NAME }}-${{ matrix.os }}-${{ matrix.arch }}
          asset_name: ${{ env.APP_NAME }}-${{ matrix.os }}-${{ matrix.arch }}
          asset_content_type: application/gzip

  tag-branch:
    name: Tag
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  
    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::$(cat VERSION)
    # Tag the repository with the release version
    - name: Set up Git
      run: |
        git config --local user.name "vertefra"
        git config --local user.email "verte.fra@gmail.com"

    - name: Tag the repository
      run: git tag -a v${{ steps.get_version.outputs.VERSION }} -m "Release v${{ steps.get_version.outputs.VERSION }}"

    - name: Push tags
      run: git push origin --tags