name: test
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  # Test
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
      
      - name: Lint Check
        run: go vet ./...

      - name: Run tests
        run: go test -v ./...
